"""empty message

Revision ID: 3bd698480c8f
Revises: cffa0dad93d1
Create Date: 2023-01-04 02:52:00.966271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd698480c8f'
down_revision = 'cffa0dad93d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('scanned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'scanned')
    # ### end Alembic commands ###
