"""empty message

Revision ID: 552b0b050812
Revises: e494153c1cd9
Create Date: 2023-03-15 12:35:55.560308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552b0b050812'
down_revision = 'e494153c1cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('otherPictures', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('trending', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farm')
    # ### end Alembic commands ###
