"""empty message

Revision ID: 6056596193a8
Revises: 62dcca0f0ac4
Create Date: 2023-01-02 16:21:22.861016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6056596193a8'
down_revision = '62dcca0f0ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'total')
    # ### end Alembic commands ###
