"""empty message

Revision ID: 62dcca0f0ac4
Revises: 862895abda81
Create Date: 2023-01-02 16:10:48.078005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dcca0f0ac4'
down_revision = '862895abda81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'active')
    # ### end Alembic commands ###
