"""empty message

Revision ID: 862895abda81
Revises: e9c96f4bf3e2
Create Date: 2023-01-02 15:17:45.676996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862895abda81'
down_revision = 'e9c96f4bf3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('totalSold', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('organiser', sa.String(), nullable=True),
    sa.Column('date_ending', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
