"""empty message

Revision ID: 9d86a1e6bb41
Revises: 9fc257a78d03
Create Date: 2023-01-02 16:43:43.836791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d86a1e6bb41'
down_revision = '9fc257a78d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'price')
    # ### end Alembic commands ###
