"""empty message

Revision ID: bc8ff23a83c7
Revises: 9d86a1e6bb41
Create Date: 2023-01-03 12:46:34.737471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8ff23a83c7'
down_revision = '9d86a1e6bb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('charges', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'charges')
    # ### end Alembic commands ###
