"""empty message

Revision ID: ca4bb9050d4c
Revises: bc8ff23a83c7
Create Date: 2023-01-04 01:19:46.096429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4bb9050d4c'
down_revision = 'bc8ff23a83c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'slug')
    # ### end Alembic commands ###
